apiVersion: v2
name: pss-baseline-policies
description: Pod Security Standards (baseline) policy set
type: application
version: 0.4.0-rc.1
appVersion: 0.1.0
keywords:
  - kubernetes
  - nirmata
  - kyverno
  - policy
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
