# -- Policies background mode
background: true

# -- Default validationFailureAction
validationFailureAction: audit

# -- Define background for specific policies.
# Override the defined `background` with a individual background for individual Policies.
backgroundByPolicy: {}
  # disallow-capabilities: false

# -- Define validationFailureActionByPolicy for specific policies.
# Override the defined `validationFailureAction` with a individual validationFailureAction for individual Policies.
validationFailureActionByPolicy: {}
  # disallow-capabilities: enforce
