apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: enable-aws-cloudtrail
  annotations:
    policies.kyverno.io/title: enable-aws-cloudtrail
    policies.kyverno.io/category: AWS S3 Security Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      CloudTrail stores Amazon S3 data event logs in an S3 bucket of your choosing.
      Consider using a bucket in a separate AWS account to better organize events from 
      multiple buckets that you might own into a central place for easier querying and
      analysis. AWS Organizations helps you create an AWS account that is linked to 
      the account that owns the bucket that you're monitoring.
spec:
  rules:
    - name: check-aws-cloudtrail-logging
      match:
        all:
        - ($analyzer.resource.type): terraform-config
        - (resource.aws_cloudtrail != null): true
      assert:
        all:
        - message: Set the enable_logging argument in aws_cloudtrail resource to true
          check:
            ~.(resource.aws_cloudtrail.values(@)[]):
              (!contains(keys(@), 'enable_logging') || enable_logging == `true`): true
                   