{{- if .Values.enabled }}
{{- $camelCaseName := "checkRdsMultiAzSupport" }}
{{- $name := "check-rds-multi-az-support" }}
{{- if not (has $name .Values.disabledPolicies) }}
apiVersion: {{ .Values.global.apiVersion | default "nirmata.io/v1alpha1" }}
kind: {{ .Values.global.policyKind | default "ValidatingPolicy" }}
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Check RDS Multi AZ Support
    policies.kyverno.io/category: AWS RDS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy checks whether high availability is enabled for your RDS DB instances.
      RDS DB instances should be configured for multiple Availability Zones (AZs). 
      This ensures the availability of the data stored. Multi-AZ deployments allow for automated failover 
      if there is an issue with AZ availability and during regular RDS maintenance.
  labels:
    app: kyverno
spec:
  failureAction: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "failureAction" }}{{ index (index .Values $camelCaseName) "failureAction" }}{{ else }}{{ .Values.failureAction | default "Audit" }}{{ end }}{{ else }}{{ .Values.failureAction | default "Audit" }}{{ end }}
  scan: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "scanner" }}{{ index (index .Values $camelCaseName) "scanner" }}{{ else if hasKey .Values "scanner" }}{{ .Values.scanner }}{{ else }}true{{ end }}{{ else if hasKey .Values "scanner" }}{{ .Values.scanner }}{{ else }}true{{ end }}
  admission: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "admission" }}{{ index (index .Values $camelCaseName) "admission" }}{{ else if hasKey .Values "admission" }}{{ .Values.admission }}{{ else }}true{{ end }}{{ else if hasKey .Values "admission" }}{{ .Values.admission }}{{ else }}true{{ end }}
  rules:
    - name: {{ $name }}
      identifier: payload.dBInstanceIdentifier
      match:
        all:
        - (metadata.provider): AWS
        - (metadata.service): RDS
        - (metadata.resource): DBInstance
      assert:
        all:
        - message: >- 
            RDS DB instances should be configured with multiple Availability Zones
          check:
            payload:
              multiAZ: true
{{- end }}
{{- end }}