{{- if .Values.enabled }}
{{- $camelCaseName := "checkRdsClusterEncryptedAtRest" }}
{{- $name := "check-rds-cluster-encrypted-at-rest" }}
{{- if not (has $name .Values.disabledPolicies) }}
apiVersion: {{ .Values.global.apiVersion | default "nirmata.io/v1alpha1" }}
kind: {{ .Values.global.policyKind | default "ValidatingPolicy" }}
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Check RDS Cluster Encrypted At Rest
    policies.kyverno.io/category: AWS RDS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy checks if an RDS DB cluster is encrypted at rest. The policy fails if an RDS DB cluster isn't encrypted at rest.
      Data at rest refers to any data that's stored in persistent, non-volatile storage for any duration. 
      Encryption helps you protect the confidentiality of such data, reducing the risk that an unauthorized user can access it. 
      Encrypting your RDS DB clusters protects your data and metadata against unauthorized access. 
      It also fulfills compliance requirements for data-at-rest encryption of production file systems.
  labels:
    app: kyverno
spec:
  failureAction: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "failureAction" }}{{ index (index .Values $camelCaseName) "failureAction" }}{{ else }}{{ .Values.failureAction | default "Audit" }}{{ end }}{{ else }}{{ .Values.failureAction | default "Audit" }}{{ end }}
  scan: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "scanner" }}{{ index (index .Values $camelCaseName) "scanner" }}{{ else if hasKey .Values "scanner" }}{{ .Values.scanner }}{{ else }}true{{ end }}{{ else if hasKey .Values "scanner" }}{{ .Values.scanner }}{{ else }}true{{ end }}
  admission: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "admission" }}{{ index (index .Values $camelCaseName) "admission" }}{{ else if hasKey .Values "admission" }}{{ .Values.admission }}{{ else }}true{{ end }}{{ else if hasKey .Values "admission" }}{{ .Values.admission }}{{ else }}true{{ end }}
  rules:
    - name: {{ $name }}
      identifier: payload.dBClusterIdentifier
      match:
        all:
        - (metadata.provider): AWS
        - (metadata.service): RDS
        - (metadata.resource): DBCluster
      assert:
        all:
        - message: >- 
            RDS DB Clusters should have encryption at-rest enabled
          check:
            payload:
              storageEncrypted: true
{{- end }}
{{- end }}
