{{- if .Values.enabled }}
{{- $camelCaseName := "checkRdsInstanceCopyTagsToSnapshotsEnabled" }}
{{- $name := "check-rds-instance-copy-tags-to-snapshots-enabled" }}
{{- if not (has $name .Values.disabledPolicies) }}
apiVersion: {{ .Values.global.apiVersion | default "nirmata.io/v1alpha1" }}
kind: {{ .Values.global.policyKind | default "ValidatingPolicy" }}
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Check RDS Instance Copy Tags To Snapshots Enabled
    policies.kyverno.io/category: AWS RDS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy checks whether RDS DB instances are configured to copy all tags to snapshots when the snapshots are created.
      Identification and inventory of your IT assets is a crucial aspect of governance and security. 
      You need to have visibility of all your RDS DB instances so that you can assess their security posture and take action on 
      potential areas of weakness. Snapshots should be tagged in the same way as their parent RDS database instances. 
      Enabling this setting ensures that snapshots inherit the tags of their parent database instances.
  labels:
    app: kyverno
spec:
  failureAction: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "failureAction" }}{{ index (index .Values $camelCaseName) "failureAction" }}{{ else }}{{ .Values.failureAction | default "Audit" }}{{ end }}{{ else }}{{ .Values.failureAction | default "Audit" }}{{ end }}
  scan: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "scanner" }}{{ index (index .Values $camelCaseName) "scanner" }}{{ else if hasKey .Values "scanner" }}{{ .Values.scanner }}{{ else }}true{{ end }}{{ else if hasKey .Values "scanner" }}{{ .Values.scanner }}{{ else }}true{{ end }}
  admission: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "admission" }}{{ index (index .Values $camelCaseName) "admission" }}{{ else if hasKey .Values "admission" }}{{ .Values.admission }}{{ else }}true{{ end }}{{ else if hasKey .Values "admission" }}{{ .Values.admission }}{{ else }}true{{ end }}
  rules:
    - name: {{ $name }}
      identifier: payload.dBInstanceIdentifier
      match:
        all:
        - (metadata.provider): AWS
        - (metadata.service): RDS
        - (metadata.resource): DBInstance
      assert:
        all:
        - message: >- 
            RDS DB instances should be configured to copy tags to snapshots
          check:
            payload:
              copyTagsToSnapshot: true
{{- end }}
{{- end }}
