{{- if .Values.enabled }}
{{- $camelCaseName := "checkDeprecatedRuntime" }}
{{- $name := "check-deprecated-runtime" }}
{{- if not (has $name .Values.disabledPolicies) }}
apiVersion: {{ .Values.global.apiVersion | default "nirmata.io/v1alpha1" }}
kind: {{ .Values.global.policyKind | default "ValidatingPolicy" }}
metadata:
  name: {{ $name }}
  annotations:
        policies.kyverno.io/title: check-deprecated-runtime
        policies.kyverno.io/category: AWS Lambda Best Practices
        policies.kyverno.io/severity: medium
        policies.kyverno.io/description: >-
            This policy ensures that Lambda Runtime is not deprecated
  labels:
    app: kyverno
spec:
  failureAction: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "failureAction" }}{{ index (index .Values $camelCaseName) "failureAction" }}{{ else }}{{ .Values.failureAction | default "Audit" }}{{ end }}{{ else }}{{ .Values.failureAction | default "Audit" }}{{ end }}
  scan: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "scanner" }}{{ index (index .Values $camelCaseName) "scanner" }}{{ else if hasKey .Values "scanner" }}{{ .Values.scanner }}{{ else }}true{{ end }}{{ else if hasKey .Values "scanner" }}{{ .Values.scanner }}{{ else }}true{{ end }}
  admission: {{ if hasKey .Values $camelCaseName }}{{ if hasKey (index .Values $camelCaseName) "admission" }}{{ index (index .Values $camelCaseName) "admission" }}{{ else if hasKey .Values "admission" }}{{ .Values.admission }}{{ else }}true{{ end }}{{ else if hasKey .Values "admission" }}{{ .Values.admission }}{{ else }}true{{ end }}
  rules:
    - name: {{ $name }}
      identifier: payload.functionName
      match:
        all:
        - (metadata.provider): "AWS"
        - (metadata.service): "Lambda"
        - (metadata.resource): "Function"
      context:
      - name: forbidden_values
        variable:
            - python3.8
            - nodejs16.x
            - dotnet7
      assert:
        all:
        - message: The runtime is deprecated for AWS lambda function, use another version.
          check:
            payload:
              (contains($forbidden_values, runtime || '')): false
{{- end }}
{{- end }}

