apiVersion: v2
name: best-practice-policies
description: Best Practice policy set
type: application
version: 0.1.1
appVersion: 0.1.0
keywords:
  - kubernetes
  - nirmata
  - kyverno
  - policy
maintainers:
  - name: Nirmata
    url: https://nirmata.com/