{{- $name := "restrict-clusterrole-nodesproxy" }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Restrict ClusterRole with Nodes Proxy
    policies.kyverno.io/category: RBAC Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ClusterRole, RBAC
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      A ClusterRole with nodes/proxy resource access allows a user to
      perform anything the kubelet API allows. It also allows users to bypass
      the API server and talk directly to the kubelet potentially circumventing
      audits and admission controllers. See https://blog.aquasec.com/privilege-escalation-kubernetes-rbac
      for more info. This policy prevents the creation
      of a ClusterRole if it contains the nodes/proxy resource.       
spec:
  validationFailureAction: {{ include "vfa-for-pol" (dict "Values" .Values "polname" $name) }}
  background: {{ include "bgscan-for-pol" (dict "Values" .Values "polname" $name) }}
  rules:
    - name: clusterrole-nodesproxy
      match:
        any:
        - resources:
            kinds:
              - ClusterRole
      validate:
        message: "A ClusterRole containing the nodes/proxy resource is not allowed."
        deny:
          conditions:
            any:
            - key: nodes/proxy
              operator: AnyIn
              value: "{{`{{`}} request.object.rules[].resources[] {{`}}`}}"
