apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: enable-s3-versioning
  annotations:
    policies.kyverno.io/title: enable-s3-versioning 
    policies.kyverno.io/category: AWS S3 Security Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Versioning in Amazon S3 is a means of keeping multiple variants of an object 
      in the same bucket. You can use the S3 Versioning feature to preserve, retrieve,
      and restore every version of every object stored in your buckets. With versioning 
      you can recover more easily from both unintended user actions and application 
      failures. After versioning is enabled for a bucket, if Amazon S3 receives multiple
      write requests for the same object simultaneously, it stores all of those objects.
spec:
  rules:
    - name: check-s3-versioning-setting
      match:
        all:
        - ($analyzer):
            resource:
              type: terraform-config
        - (planned_values.root_module.resources[?type=='aws_s3_bucket'] | length(@) > `0`): true
      assert:
        all:
        - message: Use the `aws_s3_bucket_versioning` resource to enable versioning.
          check:
            (planned_values.root_module.resources[?type=='aws_s3_bucket_versioning'] | length(@) > `0`): true
        - message: S3 Bucket Versioning needs to be set to 'Enabled'
          check:
            ~.(planned_values.root_module.resources[?type=='aws_s3_bucket_versioning']):
              (values.versioning_configuration[?status=='Enabled'] | length(@) > `0`): true
